ifndef BIOS
$(error NeoGeo BIOS not specified: use make mvs64 BIOS=<bios.bin>)
endif
ifndef ROM
$(error NeoGeo game ROM not specified: use make mvs64 ROM=<rom.zip>)
endif

BUILD_DIR = build/mvs64

include $(N64_INST)/include/n64.mk

core_src = emu.c roms.c hw.c video.c platform_n64.c sprite_cache.c lib/rdl.c $(wildcard hle_*.c)
rsp = rsp_video.S
ifdef MUSASHI
# Fallback 68k core: portable Musashi (the PC build's core). Much slower than
# m64k, but useful to isolate m64k bugs on a new game. No m64k TLB asm;
# memory goes through the banks[] callbacks in hw.c.
src = $(core_src) m68kcpu.c m68kops.c m68kdasm.c
asm =
else
# Default: fast m64k MIPS-asm 68k interpreter (0xFF000000 TLB window + hw_n64.S).
src = $(core_src) m64k/m64k.c m64k/tlb.c
asm = hw_n64.S m64k/m64k_asm.S
CFLAGS += -DUSE_M64K
endif
obj = $(src:%.c=$(BUILD_DIR)/%.o) $(asm:%.S=$(BUILD_DIR)/%.o) $(rsp:%.S=$(BUILD_DIR)/%.o)

src_makerom = mvsmakerom.c miniz.c
obj_makerom = $(src_makerom:%.c=$(BUILD_DIR)/%.o)

CFLAGS += -Wno-unused-function

ROMNAME=$(notdir $(basename $(ROM)))
ROMDIR=$(ROM:%.zip=%.n64)

all: mvsmakerom mvs64-${ROMNAME}.z64

test:
	make -f Makefile.tests all

$(BUILD_DIR)/mvs64-${ROMNAME}.dfs: $(ROM) mvsmakerom
	@echo "    [MVS] ${ROMDIR}"
	./mvsmakerom $(BIOS) $(ROM)
	@echo "    [DFS] $@"
	$(N64_MKDFS) $@ $(ROMDIR) >/dev/null

mvs64-${ROMNAME}.z64: $(BUILD_DIR)/mvs64-${ROMNAME}.dfs
mvs64-${ROMNAME}.z64: N64_ROM_TITLE="MVS64: ${ROMNAME}"
$(BUILD_DIR)/mvs64-${ROMNAME}.elf: $(obj)

mvsmakerom: $(obj_makerom)
	@echo "    [LD] $@"
	$(CC) $(LDFLAGS) -o $@ $^

clean:
	rm -f $(obj)
	rm -f $(obj_makerom)
	rm -f $(asm:%.S=$(BUILD_DIR)/%.o)
	rm -f $(rsp:%.S=$(BUILD_DIR)/%.rsp)
	rm -f $(src:%.c=$(BUILD_DIR)/%.d) $(asm:%.S=$(BUILD_DIR)/%.d)
	rm -f mvs64-*.elf
	rm -f mvs64-*.dfs
	rm -f mvs64-*.z64

-include $(src:%.c=$(BUILD_DIR)/%.d) $(asm:%.S=$(BUILD_DIR)/%.d) $(src_makerom:%.c=$(BUILD_DIR)/%.d)

.PHONY: clean test
